#!/bin/bash
cd /tmp/rec
rm -rf .repo
source build/envsetup.sh
lunch omni_shiva-eng
export SKIP_API_CHECKS=true
export SKIP_ABI_CHECKS=true
export ALLOW_MISSING_DEPENDENCIES=true
cd /tmp/rec
export CCACHE_DIR=/tmp/ccache  ##use additional flags if you need(optional)
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1

ccache -M 30G
ccache -o compression=true
ccache -z
ccache -c

mka recoveryimage

curl --upload-file ./out/target/product/shiva/recovery.img http://transfer.sh/
curl --upload-file ./out/target/product/shiva/SHRP_AddonRescue*zip https://transfer.sh/
curl --upload-file ./out/target/product/shiva/SHRP_v3.1_*zip https://transfer.sh/
echo "/nUploaded All files successfully wohoo!"
